version: "3.9"
name: "todo"
services:
  todo-db:
    image: postgres:16.0-alpine3.17
    container_name: "db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
